#include "registers.h"

DEFINE_GB_REGISTERS_GET(a, f)
DEFINE_GB_REGISTERS_GET(b, c)
DEFINE_GB_REGISTERS_GET(d, e)
DEFINE_GB_REGISTERS_GET(h, l)

DEFINE_GB_REGISTERS_SET(a, f)
DEFINE_GB_REGISTERS_SET(b, c)
DEFINE_GB_REGISTERS_SET(d, e)
DEFINE_GB_REGISTERS_SET(h, l)
